package com.example.bluetoothlescannerhr.ui.theme

import androidx.compose.ui.graphics.Color



val primaryLight = Color(0xFFADD8E6)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFADD8E6)
val onPrimaryContainerLight = Color(0xFF003366)
val secondaryLight = Color(0xFFADD8E6)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFADD8E6)
val onSecondaryContainerLight = Color(0xFF2B160A)
val tertiaryLight = Color(0xFF636032)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFEAE5AB)
val onTertiaryContainerLight = Color(0xFF1E1C00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF221A15)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF221A15)
val surfaceVariantLight = Color(0xF4DED4)
val onSurfaceVariantLight = Color(0xFF52443D)
val outlineLight = Color(0xFF85746B)
val outlineVariantLight = Color(0xFFD7C2B9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E29)
val inverseOnSurfaceLight = Color(0xFFFFEDE6)
val inversePrimaryLight = Color(0xFFADD8E6)
val surfaceDimLight = Color(0xFFE8D7CF)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1EB)
val surfaceContainerLight = Color(0xFFFCEAE3)
val surfaceContainerHighLight = Color(0xFFF6E5DD)
val surfaceContainerHighestLight = Color(0xFFF0DFD8)

// Dark Theme Colors
val primaryDark = Color(0xFFADD8E6)
val onPrimaryDark = Color(0xFF532201)
val primaryContainerDark = Color(0xFFADD8E6)
val onPrimaryContainerDark = Color(0xFFADD8E6)
val secondaryDark = Color(0xFFE6BEAB)
val onSecondaryDark = Color(0xFF432B1D)
val secondaryContainerDark = Color(0xFFADD8E6)
val onSecondaryContainerDark = Color(0xFFADD8E6)
val tertiaryDark = Color(0xFFCEC991)
val onTertiaryDark = Color(0xFF343108)
val tertiaryContainerDark = Color(0xFF4B481D)
val onTertiaryContainerDark = Color(0xFFEAE5AB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A120D)
val onBackgroundDark = Color(0xFFF0DFD8)
val surfaceDark = Color(0xFF1A120D)
val onSurfaceDark = Color(0xFFF0DFD8)
val surfaceVariantDark = Color(0xFF52443D)
val onSurfaceVariantDark = Color(0xFFD7C2B9)
val outlineDark = Color(0xFF9F8D84)
val outlineVariantDark = Color(0xFF52443D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0DFD8)
val inverseOnSurfaceDark = Color(0xFF382E29)
val inversePrimaryDark = Color(0xFF8C4E29)
val surfaceDimDark = Color(0xFF1A120D)
val surfaceBrightDark = Color(0xFF413732)
val surfaceContainerLowestDark = Color(0xFF140C09)
val surfaceContainerLowDark = Color(0xFF221A15)
val surfaceContainerDark = Color(0xFF271E19)
val surfaceContainerHighDark = Color(0xFF322823)
val surfaceContainerHighestDark = Color(0xFF3D332E)

